#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions -static-libgcc -static-libstdc++ -std=c++14 -U__STRICT_ANSI__
RESINC = 
LIBDIR = 
LIB =  -lwsock32 -lws2_32 -lpthread
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude -IC:\\boost_1_65_1
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) C:\\boost_1_65_1\\stage\\lib\\libboost_system-mgw53-mt-d-1_65_1.a
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/carnegie-esb-manager

INC_RELEASE = $(INC) -Iinclude -IC:\\boost_1_65_1
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB) C:\\boost_1_65_1\\stage\\lib\\libboost_system-mgw53-mt-1_65_1.a 
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/carnegie-esb-manager

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/server.o $(OBJDIR_DEBUG)/src/request_parser.o $(OBJDIR_DEBUG)/src/request_handler.o $(OBJDIR_DEBUG)/src/requestHandle.o $(OBJDIR_DEBUG)/src/reply.o $(OBJDIR_DEBUG)/src/mime_types.o $(OBJDIR_DEBUG)/src/connection_manager.o $(OBJDIR_DEBUG)/src/connection.o $(OBJDIR_DEBUG)/src/SystemInfo.o $(OBJDIR_DEBUG)/src/ESBManager.o $(OBJDIR_DEBUG)/src/ConnectionManager.o $(OBJDIR_DEBUG)/src/BundleMetricsHandler.o $(OBJDIR_DEBUG)/src/Bundle.o $(OBJDIR_DEBUG)/src/AppStatusHandler.o $(OBJDIR_DEBUG)/main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/server.o $(OBJDIR_RELEASE)/src/request_parser.o $(OBJDIR_RELEASE)/src/request_handler.o $(OBJDIR_RELEASE)/src/requestHandle.o $(OBJDIR_RELEASE)/src/reply.o $(OBJDIR_RELEASE)/src/mime_types.o $(OBJDIR_RELEASE)/src/connection_manager.o $(OBJDIR_RELEASE)/src/connection.o $(OBJDIR_RELEASE)/src/SystemInfo.o $(OBJDIR_RELEASE)/src/ESBManager.o $(OBJDIR_RELEASE)/src/ConnectionManager.o $(OBJDIR_RELEASE)/src/BundleMetricsHandler.o $(OBJDIR_RELEASE)/src/Bundle.o $(OBJDIR_RELEASE)/src/AppStatusHandler.o $(OBJDIR_RELEASE)/main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/server.o: src/server.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/server.cpp -o $(OBJDIR_DEBUG)/src/server.o

$(OBJDIR_DEBUG)/src/request_parser.o: src/request_parser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/request_parser.cpp -o $(OBJDIR_DEBUG)/src/request_parser.o

$(OBJDIR_DEBUG)/src/request_handler.o: src/request_handler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/request_handler.cpp -o $(OBJDIR_DEBUG)/src/request_handler.o

$(OBJDIR_DEBUG)/src/requestHandle.o: src/requestHandle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/requestHandle.cpp -o $(OBJDIR_DEBUG)/src/requestHandle.o

$(OBJDIR_DEBUG)/src/reply.o: src/reply.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/reply.cpp -o $(OBJDIR_DEBUG)/src/reply.o

$(OBJDIR_DEBUG)/src/mime_types.o: src/mime_types.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/mime_types.cpp -o $(OBJDIR_DEBUG)/src/mime_types.o

$(OBJDIR_DEBUG)/src/connection_manager.o: src/connection_manager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/connection_manager.cpp -o $(OBJDIR_DEBUG)/src/connection_manager.o

$(OBJDIR_DEBUG)/src/connection.o: src/connection.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/connection.cpp -o $(OBJDIR_DEBUG)/src/connection.o

$(OBJDIR_DEBUG)/src/SystemInfo.o: src/SystemInfo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SystemInfo.cpp -o $(OBJDIR_DEBUG)/src/SystemInfo.o

$(OBJDIR_DEBUG)/src/ESBManager.o: src/ESBManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ESBManager.cpp -o $(OBJDIR_DEBUG)/src/ESBManager.o

$(OBJDIR_DEBUG)/src/ConnectionManager.o: src/ConnectionManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ConnectionManager.cpp -o $(OBJDIR_DEBUG)/src/ConnectionManager.o

$(OBJDIR_DEBUG)/src/BundleMetricsHandler.o: src/BundleMetricsHandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BundleMetricsHandler.cpp -o $(OBJDIR_DEBUG)/src/BundleMetricsHandler.o

$(OBJDIR_DEBUG)/src/Bundle.o: src/Bundle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Bundle.cpp -o $(OBJDIR_DEBUG)/src/Bundle.o

$(OBJDIR_DEBUG)/src/AppStatusHandler.o: src/AppStatusHandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/AppStatusHandler.cpp -o $(OBJDIR_DEBUG)/src/AppStatusHandler.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/server.o: src/server.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/server.cpp -o $(OBJDIR_RELEASE)/src/server.o

$(OBJDIR_RELEASE)/src/request_parser.o: src/request_parser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/request_parser.cpp -o $(OBJDIR_RELEASE)/src/request_parser.o

$(OBJDIR_RELEASE)/src/request_handler.o: src/request_handler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/request_handler.cpp -o $(OBJDIR_RELEASE)/src/request_handler.o

$(OBJDIR_RELEASE)/src/requestHandle.o: src/requestHandle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/requestHandle.cpp -o $(OBJDIR_RELEASE)/src/requestHandle.o

$(OBJDIR_RELEASE)/src/reply.o: src/reply.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/reply.cpp -o $(OBJDIR_RELEASE)/src/reply.o

$(OBJDIR_RELEASE)/src/mime_types.o: src/mime_types.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/mime_types.cpp -o $(OBJDIR_RELEASE)/src/mime_types.o

$(OBJDIR_RELEASE)/src/connection_manager.o: src/connection_manager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/connection_manager.cpp -o $(OBJDIR_RELEASE)/src/connection_manager.o

$(OBJDIR_RELEASE)/src/connection.o: src/connection.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/connection.cpp -o $(OBJDIR_RELEASE)/src/connection.o

$(OBJDIR_RELEASE)/src/SystemInfo.o: src/SystemInfo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SystemInfo.cpp -o $(OBJDIR_RELEASE)/src/SystemInfo.o

$(OBJDIR_RELEASE)/src/ESBManager.o: src/ESBManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ESBManager.cpp -o $(OBJDIR_RELEASE)/src/ESBManager.o

$(OBJDIR_RELEASE)/src/ConnectionManager.o: src/ConnectionManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ConnectionManager.cpp -o $(OBJDIR_RELEASE)/src/ConnectionManager.o

$(OBJDIR_RELEASE)/src/BundleMetricsHandler.o: src/BundleMetricsHandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BundleMetricsHandler.cpp -o $(OBJDIR_RELEASE)/src/BundleMetricsHandler.o

$(OBJDIR_RELEASE)/src/Bundle.o: src/Bundle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Bundle.cpp -o $(OBJDIR_RELEASE)/src/Bundle.o

$(OBJDIR_RELEASE)/src/AppStatusHandler.o: src/AppStatusHandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/AppStatusHandler.cpp -o $(OBJDIR_RELEASE)/src/AppStatusHandler.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

